import 'package:flutter/material.dart';

Color color1 = Color.fromRGBO(255, 100, 100, 1.0);
Color color2 = Color.fromRGBO(255, 180, 150, 1.0);

Color color3 = Color.fromRGBO(107, 105, 255, 1.0);
Color color4 = Color.fromRGBO(107, 200, 255, 1.0);

var _casesTrendIcon = Icons.arrow_upward;
var _casesTrendColor = colorUp;
var _deathsTrendIcon = Icons.arrow_downward;
var _deathsTrendColor = colorDown;

const arrowUp = Icons.arrow_upward;
const arrowStay = Icons.arrow_forward;
const arrowDown = Icons.arrow_downward;
const colorUp = Colors.red;
const colorStay = Colors.grey;
const colorDown = Colors.green;

var _countries = <String>[
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Bolivia",
  "Bosnia-and-Herzegovina",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Burkina-Faso",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Costa-Rica",
  "Croatia",
  "Czechia",
  "Denmark",
  "DRC",
  "Ecuador",
  "Egypt",
  "El-Salvador",
  "Estonia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory-Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyzstan",
  "Lebanon",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Mexico",
  "Monaco",
  "Mongolia",
  "Morocco",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New-Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Palestine",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto-Rico",
  "Qatar",
  "Romania",
  "Russia",
  "S-Korea",
  "Saudi-Arabia",
  "Senegal",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "South-Africa",
  "South-Sudan",
  "Spain",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Thailand",
  "Tunisia",
  "Turkey",
  "UAE",
  "UK",
  "Ukraine",
  "Uruguay",
  "USA",
  "Uzbekistan",
  "Vatican-City",
  "Venezuela",
  "Vietnam",
];
